// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcypkrtcdfzyceohwuzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjeXBrcnRjZGZ6eWNlb2h3dXp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTM4MjMsImV4cCI6MjA3Mzc2OTgyM30.QNCl1_dHmRLzFIv_2tr1lCEjFpEoLnNBs6mNq1wsgNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});